# Generated by Django 5.0.3 on 2024-04-14 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_details_writer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='writer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.authors'),
        ),
    ]
